from operations import *
print("\n===== MINI LIBRARY MANAGEMENT SYSTEM DEMO =====\n")
print(add_book("B101", "Atom physics", "James kamara", "Non-Fiction", 4))
print(add_book("B102", "The Martian", "Andy Bobson", "Sci-Fi", 2))
print(add_member("M001", "Tunde Johnson", "TundeJJ23@mail.com"))
print(add_member("M002", "Bob Smith", "bob@mail.com"))
print("\nSearch results for 'James':")
print(search_books("James"))
print("\nBorrowing books...")
print(borrow_book("M001", "B101"))
print(borrow_book("M001", "B102"))
print(borrow_book("M001", "B102")) 
print("\nReturning book...")
print(return_book("M001", "B101"))
print(update_book("B102", total_copies=5))
print(delete_member("M002"))
print("\n SUCCESS") 